# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - go install -i github.com/golang/mock/mockgen
    # You may remove this if you don't use go modules.
    - go mod download
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - id: knx-exporter
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
    ldflags:
      - -X 'github.com/chr-fritz/knx-exporter/version.Version={{.Version}}'
      - -X 'github.com/chr-fritz/knx-exporter/version.Revision={{.ShortCommit}}'
      - -X 'github.com/chr-fritz/knx-exporter/version.Branch={{.Branch}}'
      - -X 'github.com/chr-fritz/knx-exporter/version.CommitDate={{.CommitTimestamp}}'
      - -s -w -extldflags '-static'
dockers:
  - goos: linux
    goarch: amd64
    ids:
      - knx-exporter

    # Templates of the Docker image names.
    image_templates:
      - "quay.io/chrfritz/knx-exporter:latest"
      - "quay.io/chrfritz/knx-exporter:{{ .Tag }}"
      - "quay.io/chrfritz/knx-exporter:v{{ .Major }}.{{ .Minor }}"
      - "quay.io/chrfritz/knx-exporter:v{{ .Major }}"

    # Skips the docker push. Could be useful if you also do draft releases.
    # If set to auto, the release will not be pushed to the docker repository
    # in case there is an indicator for prerelease in the tag e.g. v1.0.0-rc1
    # Defaults to false.
    skip_push: false

    # Path to the Dockerfile (from the project root).
    dockerfile: Dockerfile

    # Template of the docker build flags.
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.CommitDate}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.url=https://github.com/chr-fritz/knx-exporter"
      - "--label=org.opencontainers.image.licenses=Apache-2.0"
    extra_files:
      - pkg/.knx-exporter.yaml
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
