name: Release

on:
  push:
    tags:
      - '*'

permissions: { }

jobs:
  release:
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version-file: go.mod

      - name: Login to ghcr.io
        uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2 # v4.0.0
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@ec59f474b9834571250b370d4735c50f8e2d1e29 # v7.0.0
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GH_CHARTS_PRIVATE_TOKEN }}
          GOBIN: /usr/local/bin/

      - name: Helm Installation
        uses: azure/setup-helm@1a275c3b69536ee54be43f2070a358922e12c8d4 # v4.3.1
        with:
          version: "latest" # default is latest (stable)
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Helm Package
        run: helm package charts/${GITHUB_REPOSITORY#*/} --app-version "${GITHUB_REF_NAME}" --version "${GITHUB_REF_NAME#v}"

      - name: Helm Push
        run: |
          CHART_PACKAGE_NAME="${GITHUB_REPOSITORY#*/}-helm-${GITHUB_REF_NAME#v}.tgz"
          helm push "${CHART_PACKAGE_NAME}" oci://ghcr.io/$GITHUB_ACTOR
