name: Release

on:
  push:
    tags:
      - '*'

permissions: { }

jobs:
  release:
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: 'stable'
          check-latest: true

      - name: Login to ghcr.io
        uses: docker/login-action@371161bbe7024a29a25c5e19bfcbc0804fe9ad2c # v4.5.2
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@f06c13b6b1a9625abc9e6e439d9c05a8f2190e94 # v7.2.3
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GH_CHARTS_PRIVATE_TOKEN }}
          GOBIN: /usr/local/bin/

      - name: Helm Installation
        uses: azure/setup-helm@9bc31f4ebc9c6b171d7bfbaa5d006ae7abdb4310 # v5.0.1
        with:
          version: "latest" # default is latest (stable)
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Helm Package
        run: helm package charts/${GITHUB_REPOSITORY#*/} --app-version "${GITHUB_REF_NAME}" --version "${GITHUB_REF_NAME#v}"

      - name: Helm Push
        run: |
          CHART_PACKAGE_NAME="${GITHUB_REPOSITORY#*/}-helm-${GITHUB_REF_NAME#v}.tgz"
          helm push "${CHART_PACKAGE_NAME}" oci://ghcr.io/$GITHUB_ACTOR
